from app.ports.storage import IStoragePort
from fastapi import UploadFile
from typing import Protocol


class IUserAvatarService(Protocol):
    storage: IStoragePort
    bucket_name: str

    async def upload_avatar(self, file: UploadFile, user_id: int) -> None: ...
    async def upload_cover(self, file: UploadFile, user_id: int) -> None: ...
    def generate_avatar_key(self, user_id: int) -> str: ...
    def generate_upload_key(self, user_id: int) -> str: ...
    def delete(self, key: str) -> None: ...
