from typing import Protocol
import io


class IStoragePort(Protocol):
    def upload_jpeg(self, buf: io.BytesIO, bucket: str, key: str) -> None: ...
    def upload_file(
        self, buf: io.BytesIO, bucket: str, key: str, content_type: str
    ) -> None: ...
    def get_object(self, bucket: str, key: str) -> dict: ...
    def delete_object(self, bucket: str, key: str) -> None: ...
    def object_exists(self, bucket: str, key: str) -> bool: ...
    def ensure_bucket(self, bucket: str) -> None: ...
