import io
from typing import Protocol


class IStoragePort(Protocol):
    def upload_jpeg(self, buf: io.BytesIO, bucket: str, key: str) -> None: ...
    def delete_object(self, bucket: str, key: str) -> None: ...
    def object_exists(self, bucket: str, key: str) -> bool: ...
    def ensure_bucket(self, bucket: str) -> None: ...
