# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from . import auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in auth_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitUser = channel.unary_unary(
            "/auth.AuthService/InitUser",
            request_serializer=auth__pb2.UserRequest.SerializeToString,
            response_deserializer=auth__pb2.TokenPair.FromString,
            _registered_method=True,
        )
        self.GenerateKeyPair = channel.unary_unary(
            "/auth.AuthService/GenerateKeyPair",
            request_serializer=auth__pb2.UserRequest.SerializeToString,
            response_deserializer=auth__pb2.TokenPair.FromString,
            _registered_method=True,
        )
        self.GenerateAccessToken = channel.unary_unary(
            "/auth.AuthService/GenerateAccessToken",
            request_serializer=auth__pb2.AccessTokenRequest.SerializeToString,
            response_deserializer=auth__pb2.TokenResponse.FromString,
            _registered_method=True,
        )
        self.GenerateRefreshToken = channel.unary_unary(
            "/auth.AuthService/GenerateRefreshToken",
            request_serializer=auth__pb2.UserRequest.SerializeToString,
            response_deserializer=auth__pb2.TokenResponse.FromString,
            _registered_method=True,
        )
        self.ValidateRefreshToken = channel.unary_unary(
            "/auth.AuthService/ValidateRefreshToken",
            request_serializer=auth__pb2.TokenValidationRequest.SerializeToString,
            response_deserializer=auth__pb2.TokenValidationResponse.FromString,
            _registered_method=True,
        )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateKeyPair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GenerateRefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateRefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "InitUser": grpc.unary_unary_rpc_method_handler(
            servicer.InitUser,
            request_deserializer=auth__pb2.UserRequest.FromString,
            response_serializer=auth__pb2.TokenPair.SerializeToString,
        ),
        "GenerateKeyPair": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateKeyPair,
            request_deserializer=auth__pb2.UserRequest.FromString,
            response_serializer=auth__pb2.TokenPair.SerializeToString,
        ),
        "GenerateAccessToken": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateAccessToken,
            request_deserializer=auth__pb2.AccessTokenRequest.FromString,
            response_serializer=auth__pb2.TokenResponse.SerializeToString,
        ),
        "GenerateRefreshToken": grpc.unary_unary_rpc_method_handler(
            servicer.GenerateRefreshToken,
            request_deserializer=auth__pb2.UserRequest.FromString,
            response_serializer=auth__pb2.TokenResponse.SerializeToString,
        ),
        "ValidateRefreshToken": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateRefreshToken,
            request_deserializer=auth__pb2.TokenValidationRequest.FromString,
            response_serializer=auth__pb2.TokenValidationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "auth.AuthService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "auth.AuthService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/auth.AuthService/InitUser",
            auth__pb2.UserRequest.SerializeToString,
            auth__pb2.TokenPair.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateKeyPair(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/auth.AuthService/GenerateKeyPair",
            auth__pb2.UserRequest.SerializeToString,
            auth__pb2.TokenPair.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateAccessToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/auth.AuthService/GenerateAccessToken",
            auth__pb2.AccessTokenRequest.SerializeToString,
            auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GenerateRefreshToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/auth.AuthService/GenerateRefreshToken",
            auth__pb2.UserRequest.SerializeToString,
            auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateRefreshToken(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/auth.AuthService/ValidateRefreshToken",
            auth__pb2.TokenValidationRequest.SerializeToString,
            auth__pb2.TokenValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
