# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"8\n\tTokenPair\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\",\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04role\x18\x02 \x01(\t\"<\n\x12\x41\x63\x63\x65ssTokenRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"\x1e\n\rTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\"\'\n\x16TokenValidationRequest\x12\r\n\x05token\x18\x01 \x01(\t\"J\n\x17TokenValidationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0c\n\x04role\x18\x03 \x01(\t2\xcf\x02\n\x0b\x41uthService\x12.\n\x08InitUser\x12\x11.auth.UserRequest\x1a\x0f.auth.TokenPair\x12\x35\n\x0fGenerateKeyPair\x12\x11.auth.UserRequest\x1a\x0f.auth.TokenPair\x12\x44\n\x13GenerateAccessToken\x12\x18.auth.AccessTokenRequest\x1a\x13.auth.TokenResponse\x12>\n\x14GenerateRefreshToken\x12\x11.auth.UserRequest\x1a\x13.auth.TokenResponse\x12S\n\x14ValidateRefreshToken\x12\x1c.auth.TokenValidationRequest\x1a\x1d.auth.TokenValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENPAIR']._serialized_start=20
  _globals['_TOKENPAIR']._serialized_end=76
  _globals['_USERREQUEST']._serialized_start=78
  _globals['_USERREQUEST']._serialized_end=122
  _globals['_ACCESSTOKENREQUEST']._serialized_start=124
  _globals['_ACCESSTOKENREQUEST']._serialized_end=184
  _globals['_TOKENRESPONSE']._serialized_start=186
  _globals['_TOKENRESPONSE']._serialized_end=216
  _globals['_TOKENVALIDATIONREQUEST']._serialized_start=218
  _globals['_TOKENVALIDATIONREQUEST']._serialized_end=257
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_start=259
  _globals['_TOKENVALIDATIONRESPONSE']._serialized_end=333
  _globals['_AUTHSERVICE']._serialized_start=336
  _globals['_AUTHSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
