"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TokenPair(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    refresh_token: builtins.str
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "refresh_token", b"refresh_token"]) -> None: ...

global___TokenPair = TokenPair

@typing.final
class UserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    role: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        role: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["role", b"role", "user_id", b"user_id"]) -> None: ...

global___UserRequest = UserRequest

@typing.final
class AccessTokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    user_id: builtins.int
    refresh_token: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.int = ...,
        refresh_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["refresh_token", b"refresh_token", "user_id", b"user_id"]) -> None: ...

global___AccessTokenRequest = AccessTokenRequest

@typing.final
class TokenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

global___TokenResponse = TokenResponse

@typing.final
class TokenValidationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

global___TokenValidationRequest = TokenValidationRequest

@typing.final
class TokenValidationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_VALID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    ROLE_FIELD_NUMBER: builtins.int
    is_valid: builtins.bool
    user_id: builtins.int
    role: builtins.str
    def __init__(
        self,
        *,
        is_valid: builtins.bool = ...,
        user_id: builtins.int = ...,
        role: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_valid", b"is_valid", "role", b"role", "user_id", b"user_id"]) -> None: ...

global___TokenValidationResponse = TokenValidationResponse
